import type { TypingPhrase } from "./types";

export const typingPhrases: TypingPhrase[] = [
  { id: "local-game-shelf", text: "ローカルゲーム棚", reading: "ro-karu ge-mu dana" },
  { id: "quick-puzzle", text: "短いパズルを遊ぶ", reading: "mijikai pazuru wo asobu" },
  { id: "reaction-speed", text: "反応速度を測る", reading: "hannou sokudo wo hakaru" },
  { id: "clear-the-board", text: "盤面をきれいにする", reading: "banmen wo kirei ni suru" },
  { id: "calm-typing", text: "落ち着いて入力する", reading: "ochitsuite nyuuryoku suru" },
  { id: "next-game", text: "次のゲームへ進む", reading: "tsugi no ge-mu e susumu" },
  { id: "small-victory", text: "小さな勝利を重ねる", reading: "chiisana shouri wo kasaneru" },
  { id: "browser-play", text: "ブラウザで気軽に遊ぶ", reading: "burauza de kigaru ni asobu" },
  { id: "good-rhythm", text: "よいリズムで打つ", reading: "yoi rizumu de utsu" },
  { id: "one-more-round", text: "もう一回だけ挑戦", reading: "mou ikkai dake chousen" },
  { id: "morning-practice", text: "朝の練習を始める", reading: "asa no renshuu wo hajimeru" },
  { id: "coffee-break", text: "休憩にコーヒーを飲む", reading: "kyuukei ni ko-hi- wo nomu" },
  { id: "quiet-room", text: "静かな部屋で集中する", reading: "shizuka na heya de shuuchuu suru" },
  { id: "fast-fingers", text: "指先をすばやく動かす", reading: "yubisaki wo subayaku ugokasu" },
  { id: "steady-breath", text: "呼吸を整えて打つ", reading: "kokyuu wo totonoete utsu" },
  { id: "clean-desk", text: "机の上を片付ける", reading: "tsukue no ue wo katazukeru" },
  { id: "rainy-window", text: "雨の音を聞きながら", reading: "ame no oto wo kikinagara" },
  { id: "sunny-afternoon", text: "晴れた午後に遊ぶ", reading: "hareta gogo ni asobu" },
  { id: "night-session", text: "夜更けの一勝負", reading: "yofuke no hitoshoubu" },
  { id: "gentle-start", text: "ゆっくり始めて加速する", reading: "yukkuri hajimete kasoku suru" },
  { id: "look-ahead", text: "次の文字を先に見る", reading: "tsugi no moji wo saki ni miru" },
  { id: "no-panic", text: "焦らず正確に入力", reading: "aserazu seikaku ni nyuuryoku" },
  { id: "nice-combo", text: "気持ちよくコンボをつなぐ", reading: "kimochiyoku konbo wo tsunagu" },
  { id: "score-attack", text: "高得点をねらう", reading: "koutokuten wo nerau" },
  { id: "new-record", text: "自己ベストを更新する", reading: "jiko besuto wo koushin suru" },
  { id: "tiny-keyboard", text: "小さなキーボードで打つ", reading: "chiisana ki-bo-do de utsu" },
  { id: "long-sentence", text: "長い文章にも慣れていく", reading: "nagai bunshou ni mo narete iku" },
  { id: "short-word", text: "短い言葉をすばやく", reading: "mijikai kotoba wo subayaku" },
  { id: "happy-mistake", text: "間違えてもすぐ直す", reading: "machigaete mo sugu naosu" },
  { id: "typing-warmup", text: "準備運動のタイピング", reading: "junbi undou no taiping" },
  { id: "keyboard-sound", text: "軽い打鍵音が響く", reading: "karui dakkenon ga hibiku" },
  { id: "game-night", text: "今夜はゲーム日和", reading: "konya wa ge-mu biyori" },
  { id: "puzzle-master", text: "パズル名人への道", reading: "pazuru meijin e no michi" },
  { id: "brain-training", text: "頭の体操を楽しむ", reading: "atama no taisou wo tanoshimu" },
  { id: "three-minutes", text: "三分だけ遊ぶつもり", reading: "sanpun dake asobu tsumori" },
  { id: "time-flies", text: "気づけば時間が過ぎる", reading: "kizukeba jikan ga sugiru" },
  { id: "simple-rule", text: "ルールは簡単で奥深い", reading: "ru-ru wa kantan de okubukai" },
  { id: "good-flow", text: "よい流れを作る", reading: "yoi nagare wo tsukuru" },
  { id: "sharp-focus", text: "集中力を高める", reading: "shuuchuuryoku wo takameru" },
  { id: "soft-reset", text: "気分を変えて再挑戦", reading: "kibun wo kaete saichousen" },
  { id: "left-hand", text: "左手もきちんと使う", reading: "hidarite mo kichinto tsukau" },
  { id: "right-hand", text: "右手でリズムを刻む", reading: "migite de rizumu wo kizamu" },
  { id: "space-key", text: "スペースキーを忘れない", reading: "supe-su ki- wo wasurenai" },
  { id: "smooth-motion", text: "なめらかな動きで打つ", reading: "nameraka na ugoki de utsu" },
  { id: "fresh-stage", text: "新しいステージに進む", reading: "atarashii sute-ji ni susumu" },
  { id: "daily-record", text: "今日の記録を残す", reading: "kyou no kiroku wo nokosu" },
  { id: "clear-goal", text: "目標を決めて挑む", reading: "mokuhyou wo kimete idomu" },
  { id: "small-step", text: "小さな一歩を積み重ねる", reading: "chiisana ippo wo tsumikasaneru" },
  { id: "bright-screen", text: "明るい画面で遊ぶ", reading: "akarui gamen de asobu" },
  { id: "dark-mode", text: "暗い画面も悪くない", reading: "kurai gamen mo warukunai" },
  { id: "mouse-rest", text: "マウスは少し休憩", reading: "mausu wa sukoshi kyuukei" },
  { id: "keyboard-main", text: "今日はキーボードが主役", reading: "kyou wa ki-bo-do ga shuyaku" },
  { id: "playful-mood", text: "遊び心を忘れない", reading: "asobigokoro wo wasurenai" },
  { id: "quiet-win", text: "静かに勝利を味わう", reading: "shizuka ni shouri wo ajiwau" },
  { id: "another-chance", text: "もう一度チャンスを作る", reading: "mou ichido chansu wo tsukuru" },
  { id: "careful-eye", text: "目で追いながら打つ", reading: "me de oinagara utsu" },
  { id: "warm-fingers", text: "指が温まってきた", reading: "yubi ga atatamatte kita" },
  { id: "cool-head", text: "頭は冷静に保つ", reading: "atama wa reisei ni tamotsu" },
  { id: "quick-switch", text: "気持ちをすばやく切り替える", reading: "kimochi wo subayaku kirikaeru" },
  { id: "safe-pace", text: "無理のない速さで進む", reading: "muri no nai hayasa de susumu" },
  { id: "bonus-round", text: "おまけの一問に挑戦", reading: "omake no ichimon ni chousen" },
  { id: "hidden-skill", text: "隠れた実力を見せる", reading: "kakureta jitsuryoku wo miseru" },
  { id: "simple-pleasure", text: "単純な楽しさがある", reading: "tanjun na tanoshisa ga aru" },
  { id: "lucky-turn", text: "運のよい流れに乗る", reading: "un no yoi nagare ni noru" },
  { id: "steady-score", text: "安定したスコアを出す", reading: "antei shita sukoa wo dasu" },
  { id: "typing-lab", text: "タイピング研究所へようこそ", reading: "taiping kenkyuujo e youkoso" },
  { id: "play-list", text: "遊びたいゲームを選ぶ", reading: "asobitai ge-mu wo erabu" },
  { id: "home-screen", text: "ホーム画面に戻る", reading: "ho-mu gamen ni modoru" },
  { id: "fresh-idea", text: "新しいアイデアを試す", reading: "atarashii aidea wo tamesu" },
  { id: "good-design", text: "見やすいデザインにする", reading: "miyasui dezain ni suru" },
  { id: "soft-light", text: "やわらかな光が差す", reading: "yawaraka na hikari ga sasu" },
  { id: "deep-breath", text: "深呼吸してから始める", reading: "shinkokyuu shite kara hajimeru" },
  { id: "minute-focus", text: "一分間だけ集中する", reading: "ippunkan dake shuuchuu suru" },
  { id: "clear-mind", text: "頭の中を空っぽにする", reading: "atama no naka wo karappo ni suru" },
  { id: "soft-landing", text: "最後まで丁寧に打つ", reading: "saigo made teinei ni utsu" },
  { id: "next-record", text: "次はもっと伸びる", reading: "tsugi wa motto nobiru" },
  { id: "mini-game", text: "ミニゲームを増やしていく", reading: "mini ge-mu wo fuyashite iku" },
  { id: "favorite-game", text: "お気に入りを見つける", reading: "okiniiri wo mitsukeru" },
  { id: "bright-victory", text: "明るい気分で勝つ", reading: "akarui kibun de katsu" },
  { id: "quiet-challenge", text: "静かな挑戦を続ける", reading: "shizuka na chousen wo tsuzukeru" },
  { id: "gentle-finish", text: "気持ちよく終わる", reading: "kimochiyoku owaru" }
];
