import type { HangmanWord } from "./types";

export const HANGMAN_WORDS: HangmanWord[] = [
  { word: "APPLE", hint: "赤や緑の果物。パイにもよく使われます。", category: "食べ物" },
  { word: "BANANA", hint: "黄色くて細長い果物。皮をむいて食べます。", category: "食べ物" },
  { word: "ORANGE", hint: "柑橘系の果物。色の名前にもなっています。", category: "食べ物" },
  { word: "PIZZA", hint: "チーズや具材をのせて焼く丸い料理。", category: "食べ物" },
  { word: "COOKIE", hint: "サクッとした甘い焼き菓子。", category: "食べ物" },
  { word: "COFFEE", hint: "豆から作る香りの強い飲み物。", category: "飲み物" },
  { word: "WATER", hint: "生き物に欠かせない透明な飲み物。", category: "飲み物" },
  { word: "PLANET", hint: "地球や火星のように恒星の周りを回る天体。", category: "宇宙" },
  { word: "ROCKET", hint: "宇宙へ飛び立つ乗り物。", category: "宇宙" },
  { word: "GALAXY", hint: "星が大量に集まった巨大な集団。", category: "宇宙" },
  { word: "COMET", hint: "尾を引いて見えることがある小さな天体。", category: "宇宙" },
  { word: "FOREST", hint: "たくさんの木が生えている場所。", category: "自然" },
  { word: "RIVER", hint: "山から海へ流れていく水の道。", category: "自然" },
  { word: "MOUNTAIN", hint: "高く盛り上がった地形。登山の舞台。", category: "自然" },
  { word: "THUNDER", hint: "雷の音。空がゴロゴロ鳴ります。", category: "自然" },
  { word: "RAINBOW", hint: "雨上がりの空に見える七色のアーチ。", category: "自然" },
  { word: "TIGER", hint: "しま模様の大型ネコ科動物。", category: "動物" },
  { word: "RABBIT", hint: "長い耳でぴょんぴょん跳ねる動物。", category: "動物" },
  { word: "PENGUIN", hint: "南極のイメージが強い、飛べない鳥。", category: "動物" },
  { word: "DOLPHIN", hint: "海で高くジャンプする賢い哺乳類。", category: "動物" },
  { word: "GIRAFFE", hint: "とても首が長い動物。", category: "動物" },
  { word: "CASTLE", hint: "王様や騎士の物語に出てきそうな建物。", category: "建物" },
  { word: "BRIDGE", hint: "川や谷を渡るための構造物。", category: "建物" },
  { word: "SCHOOL", hint: "勉強をするために通う場所。", category: "建物" },
  { word: "LIBRARY", hint: "本を借りたり読んだりする場所。", category: "建物" },
  { word: "BICYCLE", hint: "ペダルをこいで進む二輪の乗り物。", category: "乗り物" },
  { word: "AIRPLANE", hint: "空を飛んで遠くへ移動する乗り物。", category: "乗り物" },
  { word: "TRAIN", hint: "線路の上を走る乗り物。", category: "乗り物" },
  { word: "CAMERA", hint: "写真や動画を撮る道具。", category: "道具" },
  { word: "GUITAR", hint: "弦を弾いて音を出す楽器。", category: "音楽" },
  { word: "PIANO", hint: "鍵盤を押して音を出す楽器。", category: "音楽" },
  { word: "PUZZLE", hint: "考えて解く遊び。ピースを組むものもあります。", category: "ゲーム" },
  { word: "ARCADE", hint: "昔ながらのゲームセンター風ゲームのこと。", category: "ゲーム" },
  { word: "BUTTON", hint: "押すと何かが起きる小さな部品。", category: "道具" },
  { word: "WINDOW", hint: "外を見るための開口部。PC画面の枠にも使う言葉。", category: "道具" },
  { word: "KEYBOARD", hint: "文字を入力するための道具。", category: "道具" }
];
